# -*- coding: utf-8 -*-
"""Request and Response Telegram Bot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qCPhR3LSAH7DgXqaLif8HJ8LmY7-DZYG
"""

!pip install python-telegram-bot

import logging
import math
from random import random

from telegram import Update, ForceReply
from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext

# Enable logging
logging.basicConfig(
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s', level=logging.INFO
)

logger = logging.getLogger(__name__)

token = "[your token here]"

# Define a few command handlers. These usually take the two arguments update and
# context.
def start(update: Update, _: CallbackContext) -> None:
    """Send a message when the command /start is issued."""
    user = update.effective_user
    update.message.reply_text(f'Hi {user.first_name} {user.last_name}!')


def help_command(update: Update, _: CallbackContext) -> None:
    """Send a message when the command /help is issued."""
    update.message.reply_text('Help!')


def echo(update: Update, _: CallbackContext) -> None:
    """Echo the user message."""
    update.message.reply_text(f"you said {update.message.text}")

def quadratic(update: Update, _: CallbackContext) -> None:
    #This will give us all the words in the message, which will be something like "/quadratic 1 2 3"
    all_words = update.message.text.split(" ")

    #We convert terms from index 1 to 3 to an array of integers
    terms = list(map(lambda x: int(x), all_words[1:]))
    a = terms[0]
    b = terms[1]
    c = terms[2]
    

    # discriminant
    disc = math.sqrt(b ** 2 - 4 * a *  c)

    sol1 = (-b + disc) / 2 * a
    sol2 = (-b - disc) / 2 * a

    reply = f"Your roots are {sol1} and {sol2}"

    update.message.reply_text(reply)

def cat(update: Update, _: CallbackContext) -> None:
    number = int(random() * 100000)
    url = f"https://cataas.com/cat?id={number}"
    update.message.reply_photo(url)

def main() -> None:
    """Start the bot."""
    # Create the Updater and pass it your bot's token.
    updater = Updater(token)

    # Get the dispatcher to register handlers
    dispatcher = updater.dispatcher

    # on different commands - answer in Telegram
    dispatcher.add_handler(CommandHandler("start", start))
    dispatcher.add_handler(CommandHandler("help", help_command))
    dispatcher.add_handler(CommandHandler("quadratic", quadratic))
    dispatcher.add_handler(CommandHandler("cat", cat))

    # on non command i.e message - echo the message on Telegram
    dispatcher.add_handler(MessageHandler(Filters.text, echo))

    # Start the Bot
    updater.start_polling()

    # Run the bot until you press Ctrl-C or the process receives SIGINT,
    # SIGTERM or SIGABRT. This should be used most of the time, since
    # start_polling() is non-blocking and will stop the bot gracefully.
    updater.idle()

if __name__ == '__main__':
    main()